FROM apache/airflow:2.7.3

# 1. Become root to install system tools (gcc, etc.)
USER root
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# 2. Become the airflow user again
USER airflow

# 3. Copy the file and GIVE PERMISSION to the airflow user
COPY --chown=airflow:root requirements.txt /opt/airflow/requirements.txt

# 4. Install
RUN pip install --no-cache-dir -r /opt/airflow/requirements.txt